name: memor
description: A simple reminder app.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications:
  intl:
  meta:
  path:
  path_provider:
  rxdart:

flutter:
  uses-material-design: true
  fonts:
  - family: Libertinus Sans
    fonts:
    - asset: fonts/libertinussans_regular.otf
    - asset: fonts/libertinussans_bold.otf
      weight: 700
    - asset: fonts/libertinussans_italic.otf
      style: italic
